### PR TITLE
add example of how to get contact specific properties to readme file

### PR DESCRIPTION
**Pull request by YegorChabanov**
Hey there! 

I just added an example of how to select contact specific properties while searching for a contact. I think it could be useful and save a few couple of minutes for the next developer who'll be looking for how to do it

Thank you! 
Yehor Chabanov

### CODE REVIEW

**Review by ksvirkou-hubspot — APPROVED** [review]

**Comment by pragna-php** [comment]
Hello @YegorChabanov 

I applied the same logic but I am not able to get the custom property in the filtering contacts api. For the reference below is the code.

waiting for your response!

$filter = new Filter();
$filter->setPropertyName('lastmodifieddate')
       ->setOperator('GT')
       ->setValue($updatedAt);

// Create the filter group and add the filter
$filterGroup = new FilterGroup();
$filterGroup->setFilters([$filter]);

// Create the search request and set the filter group and properties
$searchRequest = new PublicObjectSearchRequest();
$searchRequest->setFilterGroups([$filterGroup]);
$searchRequest->setProperties(['preferences']);//'firstname', 'lastname', 'email', 

// Execute the search
$response = $this->hubSpot->crm()->contacts()->searchApi()->doSearch($searchRequest);
$contactResult = $response->getResults();
dd($contactResult);

**Comment by YegorChabanov** [comment]
Hello @pragna-php! 
I'm not quite sure what your issue is. As far as I understand, you want to see the 'lastmodifieddate' property in the search results. In this case you need to specify it here: 

$searchRequest->setProperties(['lastmodifieddate']);

Also you can specify all the properties you want to see just adding other keys to array, like:

$searchRequest->setProperties(['firstname', 'lastname', 'email', 'lastmodifieddate']);

I hope this helps you.

**Comment by pragna-php** [comment]
Hello @YegorChabanov 

No, The data I am getting which needed. The concern is the "preferences" are the custom property that I have created but when try to get by below syntax, I only get the default properties and not which I set.

$searchRequest->setProperties(['firstname', 'lastname', 'email', 'preferences']);

**Comment by YegorChabanov** [comment]
Hi @pragna-php! 
That's weird. Maybe try to get all contact properties via this API endpoint https://api.hubapi.com/properties/v2/contact/properties and ensure your 'preferences' property is there and it's not hidden or deleted

**Comment by ksvirkou-hubspot** [comment]
Hi @pragna-php 
I've just tried it on my local machine and it works correctly (SDK version 11.1.0).
Try to check you imports, you need models from `HubSpot\Client\Crm\Contacts\Model`.
Do you use property name (not label)?
```php
use HubSpot\Client\Crm\Contacts\Model\FilterGroup;
use HubSpot\Client\Crm\Contacts\Model\Filter;
use HubSpot\Client\Crm\Contacts\Model\PublicObjectSearchRequest;
use HubSpot\Factory;

$hubSpot = Factory::createWithAccessToken($_ENV['HUBSPOT_PRIVATE_APP_ACCESS_TOKEN']);

$filter = new Filter();
$filter->setPropertyName('lastmodifieddate')
       ->setOperator('GT')
       ->setValue('1579514400000');

// Create the filter group and add the filter
$filterGroup = new FilterGroup();
$filterGroup->setFilters([$filter]);

// Create the search request and set the filter group and properties
$searchRequest = new PublicObjectSearchRequest();
$searchRequest->setFilterGroups([$filterGroup]);
$searchRequest->setProperties(['firstname', 'lastname', 'email','custom_property']);

// Execute the search
$response = $hubSpot->crm()->contacts()->searchApi()->doSearch($searchRequest);
$contactResult = $response->getResults();

var_dump($contactResult);
```

**Comment by pragna-php** [comment]
Hello @ksvirkou-hubspot 

Thank you for you response !

Here is the object from the properties api (https://api.hubapi.com/properties/v2/contact/properties) and I used the name in the setProperties function to fetch specific property but not working. I tried again but no success.

Also verified in composer.json, The version of package is also "11.1.0".

 ```
{
        "name": "preferences",
        "label": "Preferences",
        "description": "Customer communication preferences ",
        "groupName": "contactinformation",
        "type": "enumeration",
        "fieldType": "radio",
        "fieldLevelPermission": null,
        "hidden": false,
        "searchableInGlobalSearch": false,
        "hasUniqueValue": false,
        "externalOptionsReferenceType": null,
        "createdUserId": 68376495,
        "optionSortStrategy": null,
        "isCustomizedDefault": false,
        "sensitiveDataCategories": [],
        "optionsAreMutable": null,
        "searchTextAnalysisMode": null,
        "currencyPropertyName": null,
        "dataSensitivity": "none",
        "updatedAt": 1721649463090,
        "numberDisplayHint": "formatted",
        "referencedObjectType": null,
        "createdAt": 1721648939361,
        "formField": true,
        "displayOrder": -1,
        "readOnlyValue": false,
        "readOnlyDefinition": false,
        "mutableDefinitionNotDeletable": false,
        "favorited": false,
        "favoritedOrder": -1,
        "calculated": false,
        "externalOptions": false,
        "displayMode": "current_value",
        "showCurrencySymbol": false,
        "hubspotDefined": null,
        "deleted": false,
        "textDisplayHint": null,
        "updatedUserId": 68376495,
        "options": [
            {
                "value": "paper",
                "readOnly": false,
                "hidden": false,
                "label": "Paper Communication",
                "description": null,
                "doubleData": null,
                "displayOrder": 0
            },
            {
                "value": "paperless",
                "readOnly": false,
                "hidden": false,
                "label": "Paperless Communication",
                "description": null,
                "doubleData": null,
                "displayOrder": 1
            }
        ]
    }
```

Please let me know if I can share more details here.

**Pull request merged**
