### PR TITLE
feat: add values for IN & NOT_IN operator

### PR DESCRIPTION
**Pull request by huzaifaarain**

### CODE REVIEW

**Comment by ksvirkou-hubspot** [comment]
hi 
we can't change codegen

**Comment by huzaifaarain** [comment]
Hi, Sure no problem. 

Can we expect this in the next release as part of codegen ?

**Comment by ksvirkou-hubspot** [comment]
As soon as possible I ll publish it

**Comment by huzaifaarain** [comment]
Much obliged, thank you

**Pull request closed without merging**
