### PR TITLE
replace deprecated Guzzle functions

### PR DESCRIPTION
**Pull request by macbookandrew**
Result of https://github.com/guzzle/guzzle/pull/2712
Fixes https://github.com/HubSpot/hubspot-api-php/issues/73 and https://github.com/HubSpot/hubspot-php/issues/363

### CODE REVIEW

**Comment by atymic** [comment]
This needs to be merged :'(

**Comment by ksvirkou-hubspot** [comment]
We can't merge it because 
we would like to support both version and we can't change codegen

**Comment by Ryan-at-RoofMaxx** [comment]
@ksvirkou-hubspot 
Are there any other plans to "support both versions"?

**Comment by macbookandrew** [comment]
@ksvirkou-hubspot you would like to “support both versions” of what? As it is now, this breaks when used with Guzzle ^7.3.

**Comment by ksvirkou-hubspot** [comment]
both versions of Guzzle
I can’t merge it because we can't change codegen 
we understand the problem and working on it

**Comment by andrewminion-luminfire** [comment]
@ksvirkou-hubspot Thanks; is there an issue we can watch that will be updated when this is resolved?

**Comment by ksvirkou-hubspot** [comment]
Hi everyone 
check [this version please](https://github.com/HubSpot/hubspot-api-php/releases/tag/5.0.0)

**Pull request closed without merging**
